In [1]:
import numpy as np

## arrayを作る
#### ベクトル

In [2]:
v = np.array([1, 2, 3], dtype="float32")

In [3]:
v

array([ 1.,  2.,  3.], dtype=float32)

In [4]:
v.dtype

dtype('float32')

In [5]:
v.ndim

1

In [6]:
v.shape

(3,)

In [7]:
v.size

3

#### 行列

In [8]:
m = np.array([[1, 2, 3], [4, 5, 6]], dtype="float32")

In [9]:
m.ndim

2

In [10]:
m.shape

(2, 3)

In [11]:
m.size

6

#### arrayの作成の仕方のバリエーション

In [12]:
np.zeros([2, 3], dtype="float32")

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [13]:
np.ones([2, 3, 4], dtype="float32")

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]], dtype=float32)

## indexing、配列の要素にアクセス

In [14]:
v

array([ 1.,  2.,  3.], dtype=float32)

In [25]:
# 先頭の要素
v[0]

1.0

In [17]:
# 2番目の要素
v[1]

2.0

In [18]:
# 先頭から 2番目まで
v[0:2]

array([ 1.,  2.], dtype=float32)

In [19]:
m

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)

In [20]:
m[0, 2]
# m[0][2] と同じ

3.0

In [22]:
# : はワイルドカード的な記号、全ての行 あるいは列（その軸の全てのエントリ）を指す
m[:, 0]

array([ 1.,  4.], dtype=float32)

In [23]:
m[1, :]

array([ 4.,  5.,  6.], dtype=float32)

In [24]:
m[:, :]

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)

## arrayと数値の演算

In [26]:
v + 3
# v: [1, 2, 3]

array([ 4.,  5.,  6.], dtype=float32)

In [27]:
v * 3

array([ 3.,  6.,  9.], dtype=float32)

In [28]:
v / 3

array([ 0.33333334,  0.66666669,  1.        ], dtype=float32)

In [29]:
v ** 2

array([ 1.,  4.,  9.], dtype=float32)

In [32]:
2 * v
# right-op

array([ 2.,  4.,  6.], dtype=float32)

In [33]:
[1, 2, 3] * 3
# Python listで同じことをやってもエラーではないが、、

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [36]:
[i * 3 for i in [1, 2, 3]]
# 内包表記で同じことはできるが、NumPyの方がシンプル

[3, 6, 9]

## 関数への代入、代表値

In [37]:
np.exp(v)
# v: [1, 2, 3]

array([  2.71828175,   7.38905621,  20.08553696], dtype=float32)

In [38]:
np.log(m)

array([[ 0.        ,  0.69314718,  1.09861231],
       [ 1.38629436,  1.60943794,  1.79175949]], dtype=float32)

In [39]:
np.tanh(v)

array([ 0.76159418,  0.96402758,  0.99505478], dtype=float32)

#### 合計、平均、最大、最小

In [40]:
v

array([ 1.,  2.,  3.], dtype=float32)

In [41]:
m

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)

In [42]:
np.sum(v)

6.0

In [43]:
v.sum()

6.0

In [44]:
np.mean(m)

3.5

In [45]:
np.max(m)

6.0

In [46]:
np.min(m)

1.0

## ベクトル同士、行列同士、ベクトルと行列 等が絡んだ計算

#### ベクトル

In [47]:
v1 = np.array([1, 2, 3], dtype="float32")
v2 = np.array([2, 2, 2], dtype="float32")

In [48]:
v1 + v2

array([ 3.,  4.,  5.], dtype=float32)

In [49]:
v1 * v2

array([ 2.,  4.,  6.], dtype=float32)

In [50]:
v1 / v2

array([ 0.5,  1. ,  1.5], dtype=float32)

In [51]:
v1 ** v2

array([ 1.,  4.,  9.], dtype=float32)

#### 行列

In [52]:
m1 = np.array([[1, 2, 3], [4, 5, 6]], dtype="float32")
m2 = np.array([[2, 2, 2], [2, 2, 2]], dtype="float32")

In [64]:
%%latex
\begin{equation}
  m_1 = 
  \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6
  \end{pmatrix} \\
  m_2 =
  \begin{pmatrix}
    2 & 2 & 2 \\
    2 & 2 & 2
  \end{pmatrix}
\end{equation}

<IPython.core.display.Latex object>

In [54]:
m1 + m2

array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.]], dtype=float32)

In [55]:
m1 * m2

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]], dtype=float32)

#### ベクトルと行列、broadcasting

In [56]:
m1 + 3
# m1: [[1, 2, 3], [4, 5, 6]]

array([[ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [57]:
m2 + v1
# v1: [1, 2, 3]
# m2: [[2, 2, 2], [2, 2, 2]]

array([[ 3.,  4.,  5.],
       [ 3.,  4.,  5.]], dtype=float32)

In [59]:
## これは演習として、、？
m2 + np.array([1, 2, 3, 4], dtype="float32")

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 